/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-media-devices.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />

/**
 * `app-media-devices` is an element that enumerates the connected input devices
 * and optionally filters them, allowing the user to cycle through categories of
 * devices one at a time.
 */
interface AppMediaDevicesElement extends Polymer.Element {

  /**
   * A string used to filter the devices based on their kind property.
   * The string is converted to a RegExp, and then used to match
   * the kind property. So, it is sufficient to use a value like
   * "audioinput" or "videoinput" to select for microphones and cameras
   * respectively.
   */
  kind: string|null|undefined;

  /**
   * A list of devices whose kind properties match the configured kind
   * value.
   */
  readonly devices: any[]|null|undefined;

  /**
   * A selected device in the list of devices. This starts as the first
   * item in the devices array. The user can change this value by using
   * the selectNextDevice and selectPreviousDevice methods.
   */
  readonly selectedDevice: MediaDeviceInfo|null;

  /**
   * The index of the currently selected device.
   */
  readonly selectedDeviceIndex: number|null|undefined;

  /**
   * Select the next device in the list of devices. If the current device
   * is the last device, the first device is selected.
   */
  selectNextDevice(): void;

  /**
   * Select the previous device in the list of devices. If the current
   * device is the first device, the last device is selected.
   */
  selectPreviousDevice(): void;

  /**
   * Select a specific device from the list of devices.
   */
  selectDevice(device: any): void;
  _updateSelectedDevice(devices: any, selectedDeviceIndex: any): void;
  _updateDevices(kind: any): void;
}

interface HTMLElementTagNameMap {
  "app-media-devices": AppMediaDevicesElement;
}
