/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-media.html
 */

/// <reference path="app-media-devices.d.ts" />
/// <reference path="app-media-stream.d.ts" />
/// <reference path="app-media-video.d.ts" />
/// <reference path="app-media-audio.d.ts" />
/// <reference path="app-media-waveform.d.ts" />
/// <reference path="app-media-recorder.d.ts" />
/// <reference path="app-media-image-capture.d.ts" />

