/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-media-audio.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />

/**
 * `app-media-audio` is an element that converts an audio source to an audio
 * analyser suitable for generating audio visualizations such as the ones made by
 * `app-media-waveform`.
 */
interface AppMediaAudioElement extends Polymer.Element {

  /**
   * The input source for the element. This can be a Media Stream or a
   * Media Element (such as an audio or video element).
   */
  source: MediaStream|HTMLMediaElement|null;

  /**
   * The audio context that the analyser is associated with.
   */
  readonly context: AudioContext|null;

  /**
   * An AnalyserNode that is linked to the audio input source.
   * https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode
   */
  readonly analyser: AnalyserNode|null;

  /**
   * An AudioNode that is associated with the audio source.
   */
  readonly sourceNode: MediaStreamAudioSourceNode|MediaElementAudioSourceNode|null;
  _computeSourceNode(context: any, source: any, analyser: any): any;
  _computeAnalyser(context: any): any;
  _sourceNodeChanged(sourceNode: any, oldSourceNode: any): void;
}

interface HTMLElementTagNameMap {
  "app-media-audio": AppMediaAudioElement;
}
